---
- hosts: staging 
  tasks:

    - name: agregar host local
      command: cp /vagrant/inventory /etc/ansible/hosts

    - name: copio ansible.cfg
      command: cp /vagrant/ansible.cfg /etc/ansible/

    - name: copiar ppk
      command: cp /vagrant/id_rsa /home/vagrant/.ssh/
    
    - name: cambio permisos de key
      command: chmod 700 /home/vagrant/.ssh/id_rsa

    - name: modificar ssh_config
      command: cp /vagrant/ssh_config /etc/ssh/

    - name: cambiar permisos key
      command: chown vagrant:vagrant /home/vagrant/.ssh/id_rsa

    - name: mover index
      command: cp -r /vagrant/htdocs /home/vagrant/

    - name: permisos htdocs
      command: chown -R vagrant:vagrant /home/vagrant/htdocs

    - name: modificar index
      command: sed -i "s/replaceHostname/Staging/g" /home/vagrant/htdocs/index.html 

    - name: update cache 
      apt: update_cache=yes
        
    - name: Instalar ruby y serverspec
      command: apt-get install ruby-serverspec rake bundler -y

    - name: ejecutar script de init serverspec
      command: /vagrant/init-serverspec.sh

        #- name: Copiar archivo de pruebas
      become: yes
      become_user: root
        #   command: cp /vagrant/sample_spec.rb /home/vagrant/serverspec/spec/localhost/sample_spec.rb

        #- name: Ejecutar las pruebas
      #command: rake /home/vagrant/serverspec/spec
      #become_user: vagrant

    - name: ejecutar otro playbook.
      command: ansible-playbook -i /etc/ansible/hosts /vagrant/production.yml
      become_user: vagrant
